# Define the CPU we are working with
CPU = STM32F410xx

PERIPHS=uart pio

# Define the name of the output file
BIN = uart1.bin
# Provide a list of source files to compile
SRCS = main.c

include ../../build.mk
