# Define the CPU we are working with
CPU = STM32F410xx

PERIPHS=pio pwm

# Define the name of the output file
ELF = pwm1.elf
# Provide a list of source files to compile
SRCS = main.cpp

include ../../build.mk
