# Define the CPU we are working with
CPU = STM32F410xx

PERIPHS=uart

# Define the name of the output file
ELF = uart_dump.elf
# Provide a list of source files to compile
SRCS = main.cpp

include ../../build.mk
